Repository nasa/DS, pull requests merged in 2022-06, with the labels that each got.

#26 Fix #13 #17 #18 #19, Requirements updates
  docs/ds_FunctionalRequirements.csv
Labels: CCB:Approved

#24 Fix #23, Remove CFE_PSP_MemSet and CFE_PSP_MemSet use
  fsw/src/ds_app.c
  fsw/src/ds_file.c
  fsw/src/ds_table.c
  unit-test/ds_app_tests.c
  unit-test/ds_table_tests.c
  unit-test/utilities/ds_test_utils.c
Labels: CCB:Approved

#28 Fix #27, Updates CLA information for Apache 2.0
  .github/pull_request_template.md
  CONTRIBUTING.md
  docs/Corp_CLA_DS_260.pdf
  docs/Indv_CLA_DS_260.pdf
Labels: docs, CCB:Approved

#22 Fix #21, Added codeql-build.yml
  .github/workflows/codeql-build.yml
Labels: CCB:Approved, dependency
